# Generated by Django 3.2.4 on 2021-06-23 13:22

import database.models
import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_special_data', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=100)),
                ('fo_use_case', models.CharField(choices=[('fence', 'fence'), ('railway', 'railway'), ('underground', 'underground')], max_length=50)),
                ('midas_version', models.CharField(choices=[('midas1.0', 'midas1.0'), ('midas1.5b', 'midas1.5b'), ('midas3a', 'midas3a'), ('midas3', 'midas3'), ('midas2', 'midas2'), ('midas1.5', 'midas1.5')], max_length=50)),
                ('project', models.CharField(choices=[('konvensiyonel', 'konvensiyonel'), ('yht', 'yht'), ('aselsan', 'aselsan'), ('istanbul', 'istanbul'), ('proof_of_concept', 'proof_of_concept'), ('botas', 'botas'), ('igtas', 'igtas'), ('kayi', 'kayi'), ('middle_east', 'middle_east')], max_length=50)),
                ('region', models.CharField(choices=[('selcuk', 'selcuk'), ('balikesir', 'balikesir'), ('polatli', 'polatli'), ('sincan', 'sincan'), ('konya', 'konya'), ('macunkoy', 'macunkoy'), ('golbek', 'golbek'), ('istanbul_metrosu', 'istanbul_metrosu'), ('mebs', 'mebs'), ('osmaniye', 'osmaniye'), ('viransehir', 'viransehir'), ('idil', 'idil'), ('ceyhan', 'ceyhan'), ('silopi', 'silopi'), ('midyat', 'midyat'), ('araban', 'araban'), ('pazarcik', 'pazarcik'), ('istanbul', 'istanbul'), ('hatay', 'hatay'), ('igdir', 'igdir'), ('urdun', 'urdun'), ('suudi_arabistan', 'suudi_arabistan')], max_length=50)),
                ('territory', models.CharField(max_length=50)),
                ('record_type', models.CharField(choices=[('on_demand', 'on_demand'), ('alarm_triggered', 'alarm_triggered')], max_length=50)),
                ('activity', models.CharField(choices=[('climbing', 'climbing'), ('hitting_cable', 'hitting_cable'), ('long', 'long'), ('shaking_cable', 'shaking_cable'), ('cut', 'cut'), ('jump_and_run', 'jump_and_run'), ('stone_fall', 'stone_fall'), ('long', 'long'), ('rail_crack', 'rail_crack'), ('rail_tracker', 'rail_tracker'), ('long', 'long'), ('raining', 'raining'), ('human', 'human'), ('excavator', 'excavator'), ('vehicle', 'vehicle'), ('digging', 'digging'), ('earthquake', 'earthquake')], max_length=50)),
                ('activity_channel', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(limit_value=5150), django.core.validators.MinValueValidator(limit_value=0)])),
                ('activity_specification', models.CharField(blank=True, choices=[('walking', 'walking'), ('tum_saha_yurume', 'tum_saha_yurume'), ('running', 'running'), ('cutter', 'cutter')], max_length=50)),
                ('activity_direction', models.CharField(blank=True, choices=[('horizontal', 'horizontal'), ('vertical', 'vertical')], max_length=50)),
                ('soil_type', models.CharField(blank=True, choices=[('islaktoprak', 'islaktoprak'), ('kurutoprak', 'kurutoprak'), ('cakil-macur', 'cakil-macur'), ('beton', 'beton'), ('asfalt', 'asfalt')], max_length=50)),
                ('pulse_width', models.IntegerField(blank=True, null=True)),
                ('distance_to_fo', models.CharField(blank=True, max_length=50)),
                ('sensor_id', models.CharField(blank=True, max_length=50)),
                ('line_or_facility', models.CharField(blank=True, choices=[('line', 'line'), ('facility', 'facility')], max_length=20)),
                ('record_label', models.CharField(blank=True, choices=[('true_alarm', 'true_alarm'), ('false_alarm', 'false_alarm')], max_length=50)),
                ('insertion_date', models.DateTimeField(auto_now_add=True)),
                ('start_channel', models.PositiveIntegerField()),
                ('end_channel', models.PositiveIntegerField()),
                ('channel_num', models.PositiveIntegerField()),
                ('number_of_channels_in_one_sample', models.PositiveIntegerField()),
                ('record_size', models.BigIntegerField()),
                ('record_length_in_sec', models.IntegerField()),
                ('sampling_rate', models.IntegerField()),
                ('bin_file_hash', models.CharField(editable=False, max_length=100, unique=True)),
                ('info_file_hash', models.CharField(editable=False, max_length=100, unique=True)),
                ('time_of_day', models.CharField(max_length=50)),
                ('record_date', models.DateTimeField()),
                ('record_notes', models.TextField(blank=True, max_length=250)),
                ('at_header', djongo.models.fields.EmbeddedField(model_container=database.models.Atheader, null=True)),
                ('data_full_path', models.CharField(default='', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-insertion_date'],
            },
        ),
    ]
