# Generated by Django 3.2.4 on 2021-06-30 12:24

import analyze.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_set_name', models.CharField(max_length=50)),
                ('models_to_run', models.CharField(max_length=100)),
                ('acts_to_run', models.CharField(max_length=100)),
                ('data_set', djongo.models.fields.ArrayField(default='', model_container=analyze.models.Records_Container)),
                ('results_path', models.CharField(default='', max_length=250, unique=True)),
                ('testset_purporse', models.TextField(blank=True, default='', max_length=250)),
            ],
        ),
    ]
