# Generated by Django 3.2.4 on 2021-06-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_special_data', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=100)),
                ('fo_use_case', models.CharField(choices=[('fence', 'fence'), ('special_data', 'special_data'), ('railway', 'railway'), ('underground', 'underground')], max_length=50)),
                ('midas_version', models.CharField(choices=[('midas1.0', 'midas1.0'), ('midas1.5b', 'midas1.5b'), ('midas3a', 'midas3a'), ('midas3', 'midas3'), ('midas2', 'midas2'), ('midas1.5', 'midas1.5')], max_length=50)),
                ('project', models.CharField(choices=[('konvensiyonel', 'konvensiyonel'), ('yht', 'yht'), ('aselsan', 'aselsan'), ('istanbul', 'istanbul'), ('proof_of_concept', 'proof_of_concept'), ('botas', 'botas'), ('igtas', 'igtas'), ('kayi', 'kayi'), ('middle_east', 'middle_east')], max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('record_type', models.CharField(choices=[('alarm_triggered', 'alarm_triggered'), ('on_demand', 'on_demand')], max_length=50)),
                ('activity', models.CharField(max_length=50)),
                ('activity_channel', models.CharField(blank=True, max_length=50)),
                ('activity_specification', models.CharField(blank=True, max_length=50)),
                ('activity_direction', models.CharField(blank=True, max_length=50)),
                ('soil_type', models.CharField(blank=True, max_length=50)),
                ('pulse_width', models.IntegerField(blank=True, null=True)),
                ('distance_to_fo', models.CharField(blank=True, max_length=50)),
                ('sensor_id', models.CharField(blank=True, max_length=50)),
                ('line_or_facility', models.CharField(blank=True, max_length=20)),
                ('record_label', models.CharField(blank=True, choices=[('true_alarm', 'true_alarm'), ('false_alarm', 'false_alarm')], max_length=50)),
                ('insertion_date', models.DateTimeField(auto_now_add=True)),
                ('start_channel', models.PositiveIntegerField()),
                ('end_channel', models.PositiveIntegerField()),
                ('channel_num', models.PositiveIntegerField()),
                ('number_of_channels_in_one_sample', models.PositiveIntegerField()),
                ('record_size', models.BigIntegerField()),
                ('record_length_in_sec', models.IntegerField()),
                ('sampling_rate', models.IntegerField()),
                ('time_of_day', models.CharField(max_length=50)),
                ('record_date', models.DateTimeField()),
                ('record_notes', models.TextField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['-insertion_date'],
            },
        ),
    ]
